### ISSUE TITLE
firebase 알아보기

### ISSUE THREAD

**Issue by darae07** [darae07/silver-info#8]
아마존과 비교해 장단점 위키에 정리

**Comment by pingu9** [comment]
이거 하고있었는데 제가 정리할게요 그리고 레포 권한 열어주시면 감사하겠습니다

**Comment by darae07** [comment]
넵! 확인감사합니다! 혹시 콜라보레이터 신청 했는데 메일 왔는지 한번 봐주실수있으세요~?

**Comment by pingu9** [comment]
아 맞네요 감사합니다!

**Comment by pingu9** [comment]
고민이 정말 많이 되긴 하는데
